# Generated by Django 4.2.13 on 2024-05-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authername', models.CharField(default='Unknown Author', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('is_fav', models.BooleanField(default=False)),
                ('serving', models.CharField(default='1 serving', max_length=100)),
                ('total', models.CharField(default='0 min', max_length=100)),
                ('prep', models.CharField(default='0 min', max_length=100)),
                ('cook', models.CharField(default='0 min', max_length=100)),
                ('serving_Hours', models.IntegerField(default=2, max_length=2)),
                ('serving_minutes', models.IntegerField(default=0, max_length=2)),
                ('serving_seconds', models.IntegerField(default=0, max_length=2)),
                ('method', models.TextField(default='unknown')),
                ('calories', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('calories_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('fats', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('fats_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('carbs', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('carbs_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('protein', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('protien_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('course', models.CharField(choices=[('main_course', 'Main Course'), ('appetizers', 'Appetizers'), ('dessert', 'Dessert')], default='main_course', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient_quantity', models.CharField(max_length=100)),
                ('Ingredient_unit', models.CharField(choices=[('teaspoon', 'teaspoon'), ('clove', 'clove'), ('ounce', 'ounce'), ('kg', 'kg'), ('piece', 'piece')], default='teaspoon', max_length=20)),
                ('Ingredient_itself', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ad.recipie')),
            ],
        ),
    ]
