# Generated by Django 4.2.13 on 2024-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Recipie_of_ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='course',
            field=models.CharField(choices=[('main course', 'Main Course'), ('appetizers', 'Appetizers'), ('dessert', 'Dessert')], default='main_course', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='image',
            field=models.ImageField(upload_to='recipie/photos/'),
        ),
    ]
