# Generated by Django 4.2.13 on 2024-05-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='method',
        ),
    ]
