# Generated by Django 4.2.13 on 2024-05-23 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_recipiedetails_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='Ingredient_itself',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='Ingredient_quantity',
        ),
        migrations.AddField(
            model_name='recipie',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipie',
            name='calories_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='recipie',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipie',
            name='carbs_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='recipie',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipie',
            name='fats_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='recipie',
            name='method',
            field=models.TextField(default='lasa'),
        ),
        migrations.AddField(
            model_name='recipie',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipie',
            name='protien_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='recipie',
            name='servingTime',
            field=models.TimeField(default=2),
        ),
        migrations.AddField(
            model_name='recipie',
            name='servingTime_unit',
            field=models.CharField(choices=[('hours', 'hours'), ('minutes', 'minutes')], default='hour', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipies.recipie'),
        ),
        migrations.DeleteModel(
            name='Recipiedetails',
        ),
    ]
