# Generated by Django 4.2.13 on 2024-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_rename_name_ingredient_ingredient_itself_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='servingTime',
            field=models.TimeField(default='02:00'),
        ),
    ]
