# Generated by Django 4.2.13 on 2024-05-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_alter_recipie_servingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='servingTime',
        ),
    ]
