# Generated by Django 4.2.13 on 2024-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_remove_recipie_servingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='servingTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='calories_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='carbs_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='fats_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='protien_unit',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='servingTime_unit',
            field=models.CharField(choices=[('hours', 'hours'), ('minutes', 'minutes')], max_length=10, null=True),
        ),
    ]
