# Generated by Django 4.2.13 on 2024-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_recipie_servingtime_alter_recipie_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='servingTime',
        ),
    ]
