# Generated by Django 4.2.13 on 2024-05-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_remove_recipie_servingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipiedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servingTime', models.TimeField()),
                ('method', models.TextField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient_itself',
            new_name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='calories_unit',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='carbs_unit',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='fats_unit',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='method',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='protien_unit',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='servingTime_unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipies.recipiedetails'),
        ),
    ]
