# Generated by Django 4.2.13 on 2024-05-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0009_recipiedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Recipie',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipiedetails',
        ),
    ]
