# Generated by Django 4.2.13 on 2024-05-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipies', '0010_remove_ingredient_recipe_delete_recipie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('is_fav', models.BooleanField(default=False)),
                ('servingTime', models.TimeField(default=2)),
                ('servingTime_unit', models.CharField(choices=[('hours', 'hours'), ('minutes', 'minutes')], default='hour', max_length=10)),
                ('method', models.TextField(default='lasa')),
                ('calories', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('calories_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('fats', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('fats_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('carbs', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('carbs_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
                ('protein', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('protien_unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg')], default='g', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient_quantity', models.CharField(max_length=100)),
                ('Ingredient_itself', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipies.recipie')),
            ],
        ),
    ]
