# Generated by Django 4.2.13 on 2024-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='servingTime',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='servingTime_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Ingredient_unit',
            field=models.CharField(choices=[('teaspoon', 'teaspoon'), ('clove', 'clove'), ('ounce', 'ounce')], default='teaspoon', max_length=20),
        ),
        migrations.AddField(
            model_name='recipie',
            name='serving_Hours',
            field=models.IntegerField(default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='recipie',
            name='serving_minutes',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='recipie',
            name='serving_seconds',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='method',
            field=models.TextField(),
        ),
    ]
