# Generated by Django 4.2.13 on 2024-05-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0012_remove_recipie_servingtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipie',
            old_name='protien_unit',
            new_name='protein_unit',
        ),
    ]
