# Generated by Django 4.2.13 on 2024-05-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
