# Generated by Django 4.2.13 on 2024-05-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0017_alter_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
    ]
