# Generated by Django 4.2.13 on 2024-05-24 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipies', '0021_alter_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='Ingredient_unit',
            field=models.CharField(choices=[('teaspoon', 'teaspoon'), ('clove', 'clove'), ('ounce', 'ounce'), ('kg', 'kg'), ('piece', 'piece')], default='teaspoon', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
